### ISSUE TITLE
"This domain has expired"

### ISSUE THREAD

**Issue by rhythmichi** [tulustul/ants-life#2]
about one or two days ago, I tried to play the game. was not working, so I used [`isup.me`](url) to check if it was just me. It wasn't. It was down for everyone. So, I just sucked it up and did something  else. Today I tried to see if it was fixed but now it shows a screen with the following at the bottom, "This domain has expired. If you owned this domain, contact your domain registration service provider for further assistance. If you need help identifying your provider, visit https://www.tucowsdomains.com/" can someone fix it?

**Comment by tulustul** [comment]
The app is available here now: 
https://ants-sandbox.vercel.app/

I'm not going to extend the domain unfortunately.
Readme updated.

Closing, thanks for reporting.
